import Head from 'next/head';
import { Header, SideBar, AdminComponent } from '../../../components';

const Index = () => {
    return (
        <div>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <Header />

            <div className="flex">
                <div className="bg-[#F7FAFC] h-[830px] border-r sm:hidden md:hidden lg:block xl:block w-[200px]">
                    <SideBar active={'Importers'} />
                </div>
                <div className="flex-1">
                    <AdminComponent />
                </div>
            </div>

        </div>
    );
};

export default Index;